## Axis and keepdims Arguments

### Related APIs

np.sum / 
np.cumsum /
np.prod /
np.cumprod / 
np.diff / 
np.mean /
np.median /
np.var / 
np.std / 
np.amax / 
np.argmax / 
np.amin /
np.argmin /
np.sort / 

### sum / mean / axis /  keepdims

In [14]:
# np.sum / ndarray.sum(axis=x)
import numpy as np

a = np.arange(6).reshape((2, -1))
print('ndarray : \n', a)
print('np.sum : ', np.sum(a))
print('ndaray.sum : ', a.sum())

print('======================2D==========================')
# axis argument
a = np.arange(12).reshape((3, -1))
sum_ = a.sum(axis = 0)
sum_1 = a.sum(axis = 1)
# n_dimension : (axis = 0, axis = 1, axis = . . ., axis = n-1)

print('ndarray : {}\n{}'.format(a.shape, a))                              
print('ndarray.sum(axis = 0) : {}\n{}'.format(sum_.shape, sum_))  # axis 와 남는 vector shape 생각하기 
print('ndarray.sum(axis = 1) : {}\n{}'.format(sum_1.shape, sum_1)) # axis로 설정한 차원이 사라진다고 생각?

                ########## (3, )은 바로 broadcasting이 안되니까 (3, 1)로 바로 만들자 ==>> keepdims ##########################
    
print('========================keepdims=============================')

a = np.arange(12).reshape((3, -1))
sum_class = np.sum(a, axis = 0, keepdims = True)
sum_student = np.sum(a, axis = 1, keepdims = True)

print("scores : {}\n{}".format(a.shape, a))
print("sum_class : {}\n{}".format(sum_class.shape, sum_class))
print('sum_student : {}\n{}'.format(sum_student.shape, sum_student))

ndarray : 
 [[0 1 2]
 [3 4 5]]
np.sum :  15
ndaray.sum :  15
======================2D==========================
ndarray : (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ndarray.sum(axis = 0) : (4,)
[12 15 18 21]
ndarray.sum(axis = 1) : (3,)
[ 6 22 38]
========================keepdims=============================
scores : (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
sum_class : (1, 4)
[[12 15 18 21]]
sum_student : (3, 1)
[[ 6]
 [22]
 [38]]


In [22]:
# mean substraction
import numpy as np

n_student, n_class = 3, 4 
m_score, M_score = 0, 100
scores = np.random.randint(low = m_score,
                          high = M_score,
                          size = (n_student, n_class))

mean_class = np.mean(scores, axis = 0, keepdims = True)
mean_student = np.mean(scores, axis = 1, keepdims = True)

print('scores : \n', scores)

print('shapes : \n', scores.shape, mean_class.shape, mean_student.shape, '\n')
print('Mean substraction by classes\n', scores - mean_class)
print('Mean substraction by student\n', scores - mean_student)

scores : 
 [[27 43 52 49]
 [46 18 86 61]
 [83 60 89 77]]
shapes : 
 (3, 4) (1, 4) (3, 1) 

Mean substraction by classes
 [[-25.           2.66666667 -23.66666667 -13.33333333]
 [ -6.         -22.33333333  10.33333333  -1.33333333]
 [ 31.          19.66666667  13.33333333  14.66666667]]
Mean substraction by student
 [[-15.75   0.25   9.25   6.25]
 [ -6.75 -34.75  33.25   8.25]
 [  5.75 -17.25  11.75  -0.25]]


### 3rd order tensor case

In [38]:
import numpy as np 

print('=======================axis = 0=====================')
a = np.arange(2 * 3 * 4).reshape((2, 3, 4))

sum_ = a.sum(axis = 0, keepdims = True)
print('a : \n', a)
print('\nsum_ (axis=1): \n', sum_)
print('\nsum_shape : ', sum_.shape)
mean_ = np.mean(a, axis = 0, keepdims = True)
print('\nmean : \n', mean_)
print('\nmean_shape :', mean_.shape)

print('=========================axis = 1====================')
a = np.arange(2 * 3* 4).reshape((2, 3, 4))
sum_ = a.sum(axis = 1, keepdims = True) ## T/F 바꿔가면서 차원 차이 확인하기 
print('sum_ (axis=1):\n', sum_)
print('\nsum_shape : ',sum_.shape) # (2, 1, 4)

print('========================axis = 2=====================')
sum_ = a.sum(axis = 2, keepdims = True)
print('sum_ (axis=2):\n', sum_)
print('\nsum_shape : ', sum_.shape)

=======================axis = 0=====================
a : 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

sum_ (axis=1): 
 [[[12 14 16 18]
  [20 22 24 26]
  [28 30 32 34]]]

sum_shape :  (1, 3, 4)

mean : 
 [[[ 6.  7.  8.  9.]
  [10. 11. 12. 13.]
  [14. 15. 16. 17.]]]

mean_shape : (1, 3, 4)
=========================axis = 1====================
sum_ (axis=1):
 [[[12 15 18 21]]

 [[48 51 54 57]]]

sum_shape :  (2, 1, 4)
========================axis = 2=====================
sum_ (axis=2):
 [[[ 6]
  [22]
  [38]]

 [[54]
  [70]
  [86]]]

sum_shape :  (2, 3, 1)


In [43]:
# exercise.1
import numpy as np 

n_test, n_stuent, n_class = 4, 3, 4
m_score, M_score = 0, 100
scores = np.random.randint(low = m_score, high = M_score, size = (n_test, n_student, n_class))

print('scores : \n', scores)

for test_idx in range(n_test):
    mean = np.mean(scores[test_idx], axis=0, keepdims=True)
    mean_sub = scores[test_idx] - mean
    print(f"{test_idx}th test's mean substraction by class:\n{mean_sub}\n")

scores : 
 [[[63 30 96 30]
  [96 43 23 69]
  [ 9 73 54 26]]

 [[76 54 68 24]
  [91  1 63 85]
  [75 43 57 63]]

 [[47 11 36 98]
  [64 15 53 19]
  [30 87  4 20]]

 [[ 5  6 82 84]
  [32 88  5  8]
  [70 17 87  3]]]
0th test's mean substraction by class:
[[  7.         -18.66666667  38.33333333 -11.66666667]
 [ 40.          -5.66666667 -34.66666667  27.33333333]
 [-47.          24.33333333  -3.66666667 -15.66666667]]

1th test's mean substraction by class:
[[ -4.66666667  21.33333333   5.33333333 -33.33333333]
 [ 10.33333333 -31.66666667   0.33333333  27.66666667]
 [ -5.66666667  10.33333333  -5.66666667   5.66666667]]

2th test's mean substraction by class:
[[  0.         -26.66666667   5.          52.33333333]
 [ 17.         -22.66666667  22.         -26.66666667]
 [-17.          49.33333333 -27.         -25.66666667]]

3th test's mean substraction by class:
[[-30.66666667 -31.          24.          52.33333333]
 [ -3.66666667  51.         -53.         -23.66666667]
 [ 34.33333333 -20.   

In [46]:
# exercise.2

# case.1 (C, H, W)
import numpy as np
C, H, W = 3, 100, 200
images = np.random.randint(0, 256, size = (C, H, W))
print('shape of original image : ', images.shape,'\n')

gray_image = np.mean(images, axis =0)
print('shape of gray_scaled image : ', gray_image.shape, '\n') ################ broadcasting 가능 ################


# case.2 (H, W, C)
C, H, W = 100, 200, 3
images = np.random.randint(0, 256, size = (H, W, C))
print('shape of original image : ', images.shape, '\n')

gray_image = np.mean(images, axis = -1)
print('shape of gray_scaled image : ',gray_image.shape, '\n') ################ broadcasting 안됨 ################

shape of original image :  (3, 100, 200) 

shape of gray_scaled image :  (100, 200) 

shape of original image :  (200, 3, 100) 

shape of gray_scaled image :  (200, 3) 



## Cumsum, Prod, Diff, Statistic 

### sum / cumsum

In [60]:
# numpy.cumsum / ndarray.cumsum(a, axis = None , dtype = None ,out = None )  : 누적 합 
# sum은 scalar 값을 반환하지만, cumsum은 vector의 크기를 유지한다
import numpy as np 

a = np.arange(5)
print("ndarray : ", a)
cumsum = np.cumsum(a)
print('cumsum : ', cumsum)
# bar graph로 시각화하기 좋다

print('========================2D====================')

a = np.arange(3 *3).reshape((3, 3))
print("ndarray : {}\n{}".format(a.shape, a))

cumsum = np.cumsum(a)
print("\ncumsum : {}\n{}".format(cumsum.shape, cumsum)) # flatten 뒤에 cumsum한 것과 같다

cumsum = np.cumsum(a).reshape((3, 3))
print("\ncumsum : {}\n{}".format(cumsum.shape, cumsum))

print('==============================================')

import numpy as np

a = np.arange(3*4).reshape((3, -1))
print("ndarray : {}\n{}\n".format(a.shape, a))

cumsum = np.cumsum(a, axis = 0)
print("\ncumsum (axis = 0): {}\n{}".format(cumsum.shape, cumsum))
print("\ncumsum[::-1, :] (axis = 0): {}\n{}".format(cumsum.shape, cumsum[::-1, :]))
cumsum = np.cumsum(a, axis = 1)
print("\ncumsum (axis = 1): {}\n{}".format(cumsum.shape, cumsum))
print

ndarray :  [0 1 2 3 4]
cumsum :  [ 0  1  3  6 10]
========================2D====================
ndarray : (3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]

cumsum : (9,)
[ 0  1  3  6 10 15 21 28 36]

cumsum : (3, 3)
[[ 0  1  3]
 [ 6 10 15]
 [21 28 36]]
ndarray : (3, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


cumsum (axis = 0): (3, 4)
[[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]

cumsum[::-1, :] (axis = 0): (3, 4)
[[12 15 18 21]
 [ 4  6  8 10]
 [ 0  1  2  3]]

cumsum (axis = 1): (3, 4)
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


<function print>

### prod / cumprod

In [66]:
# np.prod, np.cumprod 

import numpy as np

a = np.arange(1,5)
print("ndarray : {}\n{}\n".format(a.shape, a))

prod = np.prod(a)
cumprod = np.cumprod(a)

print("prod : {}\n{}\n".format(prod.shape, prod))
print("cumprod : {}\n{}\n".format(cumprod.shape, cumprod))

print("===================2D======================")

a = np.arange(1, 13).reshape((3, 4))
print("ndarray : {}\n{}\n".format(a.shape, a))

prod = np.prod(a, axis = 0)
cumprod = np.cumprod(a, axis = 0)

print("prod : {}\n{}\n".format(prod.shape, prod))
print("cumprod : {}\n{}\n".format(cumprod.shape, cumprod))

ndarray : (4,)
[1 2 3 4]

prod : ()
24

cumprod : (4,)
[ 1  2  6 24]

===================2D======================
ndarray : (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

prod : (4,)
[ 45 120 231 384]

cumprod : (3, 4)
[[  4   3   2   1]
 [ 32  21  12   5]
 [384 231 120  45]]



### diff 

In [69]:
# numpy.diff(a, n=1, axis =-1 =, prepend = <no value>, append = <no value>)
# -> 방향으로 차이 a[n] -> a[n-1] - a[n]
# 벡터 크기 작아진다
import numpy as np

a = np.random.randint(0, 10, (5, ))
print("ndarray : {}\n{}\n".format(a.shape, a))

diff = np.diff(a)
print("diff : {}\n{}\n".format(diff.shape, diff))

# Used in differentiation of discrete-time signal 

print("=============================2D==========================")
np.random.seed(0)

a = np.random.randint(0, 10, (4, 4))
print("ndarray : {}\n{}\n".format(a.shape, a))

diff = np.diff(a, axis = 0) # row_diff = row_origin - 1
print("diff (axis = 0) : {}\n{}\n".format(diff.shape, diff))

diff = np.diff(a, axis = 1) # col_diff = col_origin - 1 
print("diff (axis = 1) : {}\n{}\n".format(diff.shape, diff))


ndarray : (5,)
[6 5 0 9 6]

diff : (4,)
[-1 -5  9 -3]

=============================2D==========================
ndarray : (4, 4)
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]
 [8 8 1 6]]

diff : (3, 4)
[[ 2  9  0  2]
 [-5 -5  4  1]
 [ 6  4 -6  0]]



### avg, mean, median

In [74]:
import numpy as np 

# avg : weighted mean / mean : weight = 1

# median 
x = np.arange(10) # 홀 /짝 
median = np.median(x)

print(x)
print(median)




[0 1 2 3 4 5 6 7 8 9]
4.5


In [88]:
# var, std
import numpy as np 

scores = np.random.normal(loc = 10, scale=5, size = (100, ))
var = scores.var()
std = scores.std()
var= np.var(scores)
std = np.std(scores)

print(var, std)

print('======================================')
# standardization 
means = [50, 60, 70]
stds = [3, 5, 10]
n_student, n_class = 100, 3

scores = np.random.normal(loc=means,scale=stds, size=(n_student, n_class))
scores = scores.astype(np.float32)

print("shape of scores : ", scores.shape)
print("dtype of scores : ", scores.dtype)

means = scores.mean(axis = 0)
stds = scores.std(axis= 0)

print("means before stdz : \n", means)
print("stds before stdz : \n", stds)

score_stdz = (scores - means) / stds
means_stdz = score_stdz.mean(axis = 0)
stds_stdz = score_stdz.std(axis = 0)
print("scores after stdz : \n",score_stdz)
print("means after stdz : \n",means_stdz)
print("stdz after stdz : \n",stds_stdz)

24.6226550695454 4.962122032915494
shape of scores :  (100, 3)
dtype of scores :  float32
means before stdz : 
 [50.111046 60.07277  69.82657 ]
stds before stdz : 
 [3.105734  4.8266416 9.3260145]
scores after stdz : 
 [[-0.7914455   0.31341088 -0.6314684 ]
 [ 0.55449885 -0.9684408   1.6371971 ]
 [ 0.59835935  0.05313943 -0.91817075]
 [-1.0574986  -0.94454    -1.5171113 ]
 [ 1.2590401   0.3392843   1.1665986 ]
 [ 1.6441033   1.3384583   0.5007071 ]
 [-0.43281114  0.76113564  0.24499267]
 [-0.28753194 -0.5487795   1.1758076 ]
 [ 1.3914077  -0.30006677 -0.4499937 ]
 [ 0.6386455  -0.67306626  0.66590047]
 [ 1.6420411  -0.4479184   0.04488132]
 [ 1.8861989  -0.40164784  0.16982616]
 [-0.9455069  -0.7431546  -1.459888  ]
 [ 2.789905    0.5772112  -0.03059443]
 [-1.0568316  -1.9053074   0.2778049 ]
 [-0.1759652   0.5049463   0.7609593 ]
 [ 0.94205666 -0.05876825  0.6855597 ]
 [-0.42941618 -0.8971045  -0.3440274 ]
 [ 0.70703346  0.61320496  0.00507207]
 [ 0.27569506  1.6501691  -1.9140728 ]
 

### Max, Min

In [97]:
# np.amax / ndarray.amax / numpy.argmax / ndarray.argmax

import numpy as np
a = np.random.randint(0, 100, (10, ))

M = np.max(a)
M_idx = np.argmax(a) # Max 값의 index

print(f"ndarray : \n{a}")
print(f"M / M_idx : {M}/{M_idx}")

means = [50, 60, 70]
stds = [3, 5, 10]
n_student, n_class = 100, 3 

scores = np.random.normal(loc = means, scale = stds, size = (n_student, n_class))
scores = scores.astype(np.float32)

scores_max = np.amax(scores, axis = 0, keepdims = True)
scores_max_idx = np.argmax(scores, axis = 0)
print("max scores : ", scores_max, scores_max.shape)
print("Max indices : ", scores_max_idx)

# 학생별로 시험 잘 본 과목 
score_max_idx = np.argmax(scores, axis = 1)
print("Max scores subject : ",score_max_idx)

ndarray : 
[49 69 80 76 22 50 79 39 68 39]
M / M_idx : 80/2
max scores :  [[56.9824  73.52306 89.9017 ]] (1, 3)
Max indices :  [31 62 16]
Max scores subject :  [2 2 1 2 2 2 2 2 2 2 2 1 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 1 2 2 1 2 1 2 2 2 2 2 1 1 1 2 1 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 1 2 2 2 1 2 2 2 2 2 2 1 2 2 2 1 2 2 2 2 2 2 2 2 2]


In [100]:
# numpy.amin() / ndarray.amin
# Min - Max normalization

import numpy as np
means = [50, 60, 70]
stds = [3, 5, 10]
n_student, n_class = 100, 3

scores = np.random.normal(loc=means,scale=stds,size=(n_student,n_class))
scores = scores.astype(np.float32)

scores_max = np.amax(scores, axis = 0)
scores_min = np.amin(scores, axis = 0)

scores_mM_norm = (scores - scores_min) / (scores_max - scores_min)
print(scores_mM_norm)

[[0.44109696 0.402489   0.21310215]
 [0.7208596  0.33134565 0.4527035 ]
 [0.5304412  0.42874593 0.59370446]
 [0.7513639  0.72974706 0.2718145 ]
 [0.49569324 0.6337119  0.30884182]
 [0.5236355  0.32614094 0.2717542 ]
 [0.7753249  0.44141307 0.3103032 ]
 [0.76711357 0.749799   0.23878495]
 [0.16931354 0.7257708  0.40573195]
 [0.4440334  0.11268947 0.5445547 ]
 [0.6006338  0.4574442  0.4012448 ]
 [0.40482247 0.76565784 0.2618057 ]
 [0.40309393 0.41226023 0.47783834]
 [0.57488173 0.02361332 0.45157218]
 [0.71061945 1.         0.4846987 ]
 [0.53856117 0.9126181  0.25170696]
 [0.1856075  0.3983436  0.68714195]
 [0.4539717  0.7194636  0.3488553 ]
 [0.810822   0.8307201  0.6988698 ]
 [0.51786834 0.5825487  0.29769963]
 [0.342949   0.60626346 0.3705861 ]
 [0.4292853  0.80963343 0.        ]
 [0.26476255 0.16977984 0.31576815]
 [0.51695997 0.6817055  0.6846458 ]
 [0.55343103 0.6024009  0.43136021]
 [0.4017033  0.31777987 0.36662182]
 [0.3618925  0.5918223  0.35007554]
 [0.33542943 0.54523426 0.64

In [115]:
# Maximum, minimum 

import numpy as np

u = np.random.randint(0, 10, (3, 4))
v = np.random.randint(0, 10, (3, 4))
print(f"u : {u.shape}\n{u}\n")
print(f"v : {v.shape}\n{v}\n")

maximum = np.maximum(u, v)
minimum = np.minimum(u, v)

print(f'Maximum :\n{maximum}\n')
print(f'minimum :\n{minimum}\n')

print("==================================")

u = np.random.randint(0, 10, (10, ))
v = np.random.randint(0, 10, (10, ))
print(f"u : {u.shape}\n{u}\n")
print(f"v : {v.shape}\n{v}\n")

maximum = np.zeros_like(u)
maximum[u >= v] = u[u >= v]
maximum[u < v] = v[u < v]

print(f"maximum : \n{maximum}") # np.maximum과 같다 


print("====================================")
u = np.random.randint(0, 10, (10, ))
v = np.random.randint(0, 10, (10, ))
print(f"u : {u.shape}\n{u}\n")
print(f"v : {v.shape}\n{v}\n")

# up_vals = np.full_like(u, fill_value=100)
# down_vals = np.full_like(u, fill_value = -100)

#################
maximum_where = np.where(u > v, u, v)
print(f'Maximum_where : {maximum_where}')

minimum_where = np.where(u > v, v, u)
print(f'minimum_where : {minimum_where}')

u : (3, 4)
[[0 8 0 7]
 [2 2 2 2]
 [5 8 4 3]]

v : (3, 4)
[[9 0 6 1]
 [6 9 1 6]
 [9 6 6 6]]

Maximum :
[[9 8 6 7]
 [6 9 2 6]
 [9 8 6 6]]

minimum :
[[0 0 0 1]
 [2 2 1 2]
 [5 6 4 3]]

u : (10,)
[4 8 3 0 0 7 3 1 3 6]

v : (10,)
[6 3 9 4 6 1 4 1 5 3]

maximum : 
[6 8 9 4 6 7 4 1 5 6]
u : (10,)
[2 2 2 8 0 1 5 4 0 6]

v : (10,)
[2 5 7 9 2 9 1 9 1 8]

Maximum_where : [2 5 7 9 2 9 5 9 1 8]
minimum_where : [2 2 2 8 0 1 1 4 0 6]


## Rounding and Sorting

Rounding : 결과를 출력할 때, 쉽게 볼 수 있도록

### Rounding

In [121]:
# numpy.around / numpy.round_ / ndarray.round(decimals = 0, out = None)
# decimals : 표기할 자리수 --- decimals = 2 일때, 셋째자리에서 반올림 
# decimals 는 기본 0이므로 첫째자리에서 반올림한 정수부분만 표현 

import numpy as np

x = np.random.uniform(-5, 5, (5, ))

np_around = np.around(x, decimals=2)
x_round = x.round(decimals = 2)  

print(x)
print(np_around)
print(x_round)

print("\n")

scores = np.random.uniform(0, 100, (100, 5))
means = scores.mean(axis=0)
stds = scores.std(axis =0)

print(f'class means : {means.round(2)}\n')
print(f'class stds : {stds.round(2)}')

[-3.83080877  0.8822204  -4.68292254 -1.5515885  -4.26012006]
[-3.83  0.88 -4.68 -1.55 -4.26]
[-3.83  0.88 -4.68 -1.55 -4.26]


class means : [50.16 53.84 47.33 50.09 48.58]

class stds : [29.02 31.38 28.28 27.72 30.31]


In [7]:
# numpy.ceil / numpy.floor : 소숫점 첫째자리에서 올림, 내림

import numpy as np

x = np.random.uniform(-5, 5, (5, ))

ceil = np.ceil(x)
floor = np.floor(x)

print(f'x : \n{x}\n')
print(f'ceil : \n{ceil}\n')
print(f'floor : \n{floor}\n')

print("===================")

# numpy.trunc : 소숫점 첫째자리까지 그냥 날리고 정수부분만 
x = np.random.uniform(-5, 5, (5, ))

trunc = np.trunc(x)
print(f'x : \n{x}\n')
print(f'trunc : \n{trunc}')

trunc_where = np.where(x >=0, np.floor(x), np.ceil(x))
print(f'trunc_where : \n{trunc_where}\n')

# 둘째자리에서 버리기

trunc = 0.1 * np.trunc(10*x)
print(f'trunc(0.1) : \n{trunc}\n')

# 정수부, 소수부 나누기
int_part = np.trunc(x)
frac_part = x - int_part
print(f"frac_part = \n{frac_part}\n")

x : 
[ 0.90132835  3.31133002  3.11448143  2.90359421 -4.25913626]

ceil : 
[ 1.  4.  4.  3. -4.]

floor : 
[ 0.  3.  3.  2. -5.]

x : 
[ 4.49992855 -4.975055    0.63976884  3.71092602  4.35289236]

trunc : 
[ 4. -4.  0.  3.  4.]
trunc_where : 
[ 4. -4.  0.  3.  4.]

trunc(0.1) : 
[ 4.4 -4.9  0.6  3.7  4.3]

frac_part = 
[ 0.49992855 -0.975055    0.63976884  0.71092602  0.35289236]



### Sorting

In [7]:
# numpy.sort() / numpy.argsort()
import numpy as np

x = np.random.randint(0, 20, (20, ))

sorted_x = np.sort(x)
argsort_x = np.argsort(x)

print(f'origin : {x}\n')
print(f'sort : {sorted_x}\n')
print(f'argsort_x : {argsort_x}\n')

sort = np.sort(x)[::-1]
argsort = np.argsort(x)[::-1]
print(f'sort : {sort}')

# 
print('================================')
pred = np.random.uniform(0, 100, (5, ))
pred /= pred.sum()

top3_pred = np.sort(pred)[::-1][:3]
top3_indices = np.argsort(pred)[::-1][:3]

print(f'pred : \n{pred.round(3)}\n')
print(f'top3_pred : \n{top3_pred.round(3)}')
print(f'top-3 indices : \n{top3_indices}')


origin : [12  5 18  2  1 11  4  7 14 17 17  5 16 15  3  5  3  6  6  3]

sort : [ 1  2  3  3  3  4  5  5  5  6  6  7 11 12 14 15 16 17 17 18]

argsort_x : [ 4  3 19 16 14  6  1 15 11 17 18  7  5  0  8 13 12 10  9  2]

sort : [18 17 17 16 15 14 12 11  7  6  6  5  5  5  4  3  3  3  2  1]
pred : 
[0.243 0.185 0.243 0.124 0.205]

top3_pred : 
[0.243 0.243 0.205]
top-3 indices : 
[2 0 4]


In [81]:
# sorting matrix  (row)
import numpy as np

x = np.random.randint(0, 100, (4, 5))

sort = np.sort(x, axis = 0)
argsort = np.argsort(x, axis = 0)

print(f'x : \n{x}\n')
print(f'sort_x : \n{sort}\n')
print(f'argsort : \n{argsort}\n')

sort = sort[:, 0]
print(f'sort_x : \n{sort}\n')  # 첫번째 행만 뽑기

print('====================================================')

sort = np.sort(x, axis = 0)[::-1, :]
argsort = np.argsort(x, axis = 0)[::-1, :]

print(f'x : \n{x}\n')
print(f'sort_x : \n{sort}\n')
print(f'argsort_x : \n{argsort}\n')

x : 
[[90 55 20 89 19]
 [93 33 11 66 21]
 [88 99  8 66 87]
 [74 69 14 56 78]]

sort_x : 
[[74 33  8 56 19]
 [88 55 11 66 21]
 [90 69 14 66 78]
 [93 99 20 89 87]]

argsort : 
[[3 1 2 3 0]
 [2 0 1 1 1]
 [0 3 3 2 3]
 [1 2 0 0 2]]

sort_x : 
[74 88 90 93]

x : 
[[90 55 20 89 19]
 [93 33 11 66 21]
 [88 99  8 66 87]
 [74 69 14 56 78]]

sort_x : 
[[93 99 20 89 87]
 [90 69 14 66 78]
 [88 55 11 66 21]
 [74 33  8 56 19]]

argsort_x : 
[[1 2 0 0 2]
 [0 3 3 2 3]
 [2 0 1 1 1]
 [3 1 2 3 0]]



In [84]:
# sorting matirx

import numpy as np 

scores = np.random.randint(0, 100, (5, 3))
sort = np.sort(scores, axis = 0)[::-1, :]
argsort = np.argsort(scores, axis = 0)[::-1, :]
top2_scores = sort[:2, :]
top2_students = argsort[:2, :]

print(f'scores : \n{scores}\n')
print(f'sort : \n{sort}\n')
print(f'argsort : \n{argsort}\n')
print(f'top2-scores : \n{top2_scores}\n')
print(f'top2-students : \n{top2_students}\n')

print("=========================================")

# column 

x = np.random.randint(0, 100, (4, 5))

sort_ascending = np.sort(x, axis = 1)
argsort_ascending = np.argsort(x, axis = 1)

sort_decending = np.sort(x, axis = 1)[:, ::-1]
argsort_decending = np.argsort(x, axis = 1)[:, ::-1]

print(f'x : \n{x}\n')
print(f'ascending : \n{sort_ascending}\n')
print(f'argsort_ascending : \n{argsort_ascending}\n')
print(f'decending : \n{sort_decending}\n')
print(f'argsort_decending : \n{argsort_decending}\n')

scores : 
[[ 4 30 97]
 [78 43 51]
 [93 32 55]
 [69 71 11]
 [ 1 83 48]]

sort : 
[[93 83 97]
 [78 71 55]
 [69 43 51]
 [ 4 32 48]
 [ 1 30 11]]

argsort : 
[[2 4 0]
 [1 3 2]
 [3 1 1]
 [0 2 4]
 [4 0 3]]

top2-scores : 
[[93 83 97]
 [78 71 55]]

top2-students : 
[[2 4 0]
 [1 3 2]]

x : 
[[44 45  8 46 33]
 [37 69 96 71 50]
 [27  9 27 21 52]
 [76 62 96 26 72]]

ascending : 
[[ 8 33 44 45 46]
 [37 50 69 71 96]
 [ 9 21 27 27 52]
 [26 62 72 76 96]]

argsort_ascending : 
[[2 4 0 1 3]
 [0 4 1 3 2]
 [1 3 0 2 4]
 [3 1 4 0 2]]

decending : 
[[46 45 44 33  8]
 [96 71 69 50 37]
 [52 27 27 21  9]
 [96 76 72 62 26]]

argsort_decending : 
[[3 1 0 4 2]
 [2 3 1 4 0]
 [4 2 0 3 1]
 [2 0 4 1 3]]

